apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cnv-console-monitor-data
  labels:
    app: cnv-console-monitor
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
