apiVersion: v1
kind: Service
metadata:
  name: cnv-ui-monitor
  labels:
    app: cnv-ui-monitor
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: cnv-ui-monitor-tls
spec:
  selector:
    app: cnv-ui-monitor
  ports:
    - port: 443
      targetPort: 8443
      protocol: TCP
      name: proxy
  type: ClusterIP
