apiVersion: v1
kind: ServiceAccount
metadata:
  name: cnv-ui-monitor
  labels:
    app: cnv-ui-monitor
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.primary: >-
      {"kind":"OAuthRedirectReference","apiVersion":"v1",
       "reference":{"kind":"Route","name":"cnv-ui-monitor"}}
