import type { ChangelogItem, ChangelogResult } from '../../api/ai';

import { CATEGORY_LABELS } from './changelogConstants';

const MAX_SLACK_ITEMS = 15;
const PRINT_DELAY_MS = 500;

export const buildSlackText = (result: ChangelogResult): string => {
  const { changelog } = result;
  const lines: string[] = [];
  lines.push(`:rocket: *${result.meta.label} Changelog*`);
  if (changelog.summary) {
    lines.push(`> ${changelog.summary}`);
  }
  if (changelog.categories) {
    for (const [cat, items] of Object.entries(changelog.categories)) {
      // eslint-disable-next-line @typescript-eslint/no-unnecessary-condition -- defensive: runtime data
      if (!items?.length) {
        continue;
      }
      // eslint-disable-next-line @typescript-eslint/no-unnecessary-condition -- defensive: runtime data
      const label = CATEGORY_LABELS[cat]?.label ?? cat;
      lines.push(`\n*${label} (${items.length}):*`);
      items.slice(0, MAX_SLACK_ITEMS).forEach((item: ChangelogItem) => {
        lines.push(
          `• ${item.key ? `<https://issues.redhat.com/browse/${item.key}|${item.key}>` : ''} ${item.title || ''}`,
        );
        if (item.ticketSummary) {
          lines.push(`  _${item.ticketSummary}_`);
        }
      });
      if (items.length > MAX_SLACK_ITEMS) {
        lines.push(`_...and ${items.length - MAX_SLACK_ITEMS} more_`);
      }
    }
  }
  return lines.join('\n');
};

export const openPrintView = (
  result: ChangelogResult,
  reportRef: React.RefObject<HTMLDivElement | null>,
) => {
  if (!reportRef.current) {
    return;
  }
  const printWindow = window.open('', '_blank');
  if (!printWindow) {
    return;
  }
  printWindow.document.write(`<html><head><title>${result.meta.label} Changelog</title>
    <style>body{font-family:RedHatText,-apple-system,sans-serif;padding:40px;max-width:800px;margin:0 auto;color:#151515}h1{font-size:22px;border-bottom:2px solid #06c;padding-bottom:8px}h2{font-size:16px;color:#06c;margin-top:20px}.item{padding:3px 0;border-bottom:1px solid #eee;font-size:13px}.key{font-weight:600;min-width:90px;display:inline-block}.badge{display:inline-block;padding:1px 6px;border-radius:8px;font-size:10px;font-weight:600}.summary{padding:12px;background:#f0f0f0;border-left:4px solid #06c;border-radius:4px;margin:12px 0}.footer{margin-top:24px;font-size:10px;color:#6a6e73;border-top:1px solid #d2d2d2;padding-top:8px}</style></head>
    <body><h1>${result.meta.label} Changelog</h1><p>Generated: ${new Date().toLocaleString()}</p>${reportRef.current.innerHTML}<div class="footer">Generated by CNV Console Monitor</div></body></html>`);
  printWindow.document.close();
  setTimeout(() => printWindow.print(), PRINT_DELAY_MS);
};
