import { useRef, useState } from 'react';

import type { ChecklistTask, ReleaseInfo } from '@cnv-monitor/shared';

import {
  Button,
  ClipboardCopy,
  ClipboardCopyVariant,
  Modal,
  ModalBody,
  ModalFooter,
  ModalHeader,
  ModalVariant,
  Tab,
  Tabs,
  TabTitleText,
} from '@patternfly/react-core';
import { CopyIcon, DownloadIcon, FileAltIcon } from '@patternfly/react-icons';

import type { VersionReadiness } from '../../api/releases';

import { ReportVisualTab } from './ReportVisualTab';
import { useReleaseReport } from './useReleaseReport';

const PRINT_DELAY_MS = 500;

type ReleaseReportProps = {
  release: ReleaseInfo;
  checklist?: ChecklistTask[];
  readiness?: VersionReadiness | null;
};

export const ReleaseReport = ({ checklist, readiness, release }: ReleaseReportProps) => {
  const [isOpen, setIsOpen] = useState(false);
  const [activeTab, setActiveTab] = useState(0);
  const reportRef = useRef<HTMLDivElement>(null);

  const report = useReleaseReport(release, checklist, readiness);

  const handleDownloadPdf = () => {
    if (!reportRef.current) {
      return;
    }
    const printWindow = window.open('', '_blank');
    if (!printWindow) {
      return;
    }
    printWindow.document.write(`
      <html><head><title>${report.version} Release Report</title>
      <style>
        body { font-family: RedHatText, -apple-system, sans-serif; padding: 40px; color: #151515; max-width: 800px; margin: 0 auto; }
        h1 { font-size: 24px; border-bottom: 2px solid #06c; padding-bottom: 8px; }
        h2 { font-size: 18px; margin-top: 24px; color: #06c; }
        h3 { font-size: 14px; margin-top: 16px; }
        table { width: 100%; border-collapse: collapse; margin: 8px 0; }
        th, td { text-align: left; padding: 6px 12px; border-bottom: 1px solid #d2d2d2; font-size: 13px; }
        th { background: #f0f0f0; font-weight: 600; }
        .metric { display: inline-block; text-align: center; padding: 12px 24px; margin: 4px; border: 1px solid #d2d2d2; border-radius: 6px; }
        .metric-value { font-size: 28px; font-weight: 700; display: block; }
        .metric-label { font-size: 11px; color: #6a6e73; }
        .badge { display: inline-block; padding: 2px 8px; border-radius: 10px; font-size: 11px; font-weight: 600; }
        .badge-green { background: #e7f5e1; color: #3e8635; }
        .badge-red { background: #fce7e7; color: #c9190b; }
        .badge-orange { background: #fef3e0; color: #ec7a08; }
        .footer { margin-top: 32px; font-size: 11px; color: #6a6e73; border-top: 1px solid #d2d2d2; padding-top: 8px; }
      </style></head><body>
      <h1>${report.version} Release Report</h1>
      <p>Generated: ${new Date().toLocaleString()}</p>
      ${reportRef.current.innerHTML}
      <div class="footer">Generated by CNV Console Monitor</div>
      </body></html>
    `);
    printWindow.document.close();
    setTimeout(() => printWindow.print(), PRINT_DELAY_MS);
  };

  return (
    <>
      <Button icon={<FileAltIcon />} size="sm" variant="secondary" onClick={() => setIsOpen(true)}>
        Generate Report
      </Button>
      <Modal isOpen={isOpen} variant={ModalVariant.large} onClose={() => setIsOpen(false)}>
        <ModalHeader title={`${report.version} Release Report`} />
        <ModalBody>
          <Tabs activeKey={activeTab} onSelect={(_e, k) => setActiveTab(k as number)}>
            <Tab eventKey={0} title={<TabTitleText>Visual Report</TabTitleText>}>
              <ReportVisualTab
                byAssignee={report.byAssignee}
                byPriority={report.byPriority}
                checklistPct={report.checklistPct}
                closedItems={report.closedItems}
                isHealthy={report.isHealthy}
                openItems={report.openItems}
                passRate={report.passRate}
                readiness={readiness}
                ref={reportRef}
                release={release}
                totalItems={report.totalItems}
                version={report.version}
              />
            </Tab>
            <Tab eventKey={1} title={<TabTitleText>Slack Format</TabTitleText>}>
              <ClipboardCopy isBlock className="app-mt-md" variant={ClipboardCopyVariant.expansion}>
                {report.slackReport}
              </ClipboardCopy>
            </Tab>
          </Tabs>
        </ModalBody>
        <ModalFooter>
          <Button icon={<DownloadIcon />} variant="primary" onClick={handleDownloadPdf}>
            Download PDF
          </Button>
          <Button
            icon={<CopyIcon />}
            variant="secondary"
            onClick={() => navigator.clipboard.writeText(report.slackReport)}
          >
            Copy Slack
          </Button>
          <Button variant="link" onClick={() => setIsOpen(false)}>
            Close
          </Button>
        </ModalFooter>
      </Modal>
    </>
  );
};
