import React, { useMemo, useRef, useState } from 'react';

import type { ChecklistTask, ReleaseInfo } from '@cnv-monitor/shared';

import {
  Alert,
  Button,
  ClipboardCopy,
  ClipboardCopyVariant,
  Content,
  DescriptionList,
  DescriptionListDescription,
  DescriptionListGroup,
  DescriptionListTerm,
  Divider,
  Flex,
  FlexItem,
  Label,
  Modal,
  ModalBody,
  ModalFooter,
  ModalHeader,
  ModalVariant,
  Progress,
  ProgressMeasureLocation,
  ProgressSize,
  Tab,
  Tabs,
  TabTitleText,
} from '@patternfly/react-core';
import { CopyIcon, DownloadIcon, FileAltIcon } from '@patternfly/react-icons';

import type { VersionReadiness } from '../../api/releases';

type ReleaseReportProps = {
  release: ReleaseInfo;
  checklist?: ChecklistTask[];
  readiness?: VersionReadiness | null;
};

export const ReleaseReport: React.FC<ReleaseReportProps> = ({ checklist, readiness, release }) => {
  const [isOpen, setIsOpen] = useState(false);
  const [activeTab, setActiveTab] = useState(0);
  const reportRef = useRef<HTMLDivElement>(null);

  const version = release.shortname.replace('cnv-', 'CNV ');
  const openItems = (checklist ?? []).filter(task => task.status !== 'Closed');
  const closedItems = (checklist ?? []).filter(task => task.status === 'Closed');
  const totalItems = (checklist ?? []).length;
  const checklistPct = totalItems > 0 ? Math.round((closedItems.length / totalItems) * 100) : 100;
  const passRate = readiness?.passRate ?? null;
  const isHealthy = checklistPct >= 80 && (passRate === null || passRate >= 85);

  const byPriority = useMemo(() => {
    const map = new Map<string, typeof openItems>();
    for (const item of openItems) {
      const priority = item.priority || 'Unset';
      if (!map.has(priority)) {
        map.set(priority, []);
      }
      map.get(priority)?.push(item);
    }
    return [...map.entries()].sort((entryA, entryB) => {
      const order = ['Blocker', 'Critical', 'Major', 'Minor', 'Trivial', 'Unset'];
      return order.indexOf(entryA[0]) - order.indexOf(entryB[0]);
    });
  }, [openItems]);

  const byAssignee = useMemo(() => {
    const map = new Map<string, number>();
    for (const item of openItems) {
      map.set(item.assignee || 'Unassigned', (map.get(item.assignee || 'Unassigned') ?? 0) + 1);
    }
    return [...map.entries()].sort((entryA, entryB) => entryB[1] - entryA[1]);
  }, [openItems]);

  const handleDownloadPdf = () => {
    if (!reportRef.current) {
      return;
    }
    const printWindow = window.open('', '_blank');
    if (!printWindow) {
      return;
    }
    printWindow.document.write(`
      <html><head><title>${version} Release Report</title>
      <style>
        body { font-family: RedHatText, -apple-system, sans-serif; padding: 40px; color: #151515; max-width: 800px; margin: 0 auto; }
        h1 { font-size: 24px; border-bottom: 2px solid #06c; padding-bottom: 8px; }
        h2 { font-size: 18px; margin-top: 24px; color: #06c; }
        h3 { font-size: 14px; margin-top: 16px; }
        table { width: 100%; border-collapse: collapse; margin: 8px 0; }
        th, td { text-align: left; padding: 6px 12px; border-bottom: 1px solid #d2d2d2; font-size: 13px; }
        th { background: #f0f0f0; font-weight: 600; }
        .metric { display: inline-block; text-align: center; padding: 12px 24px; margin: 4px; border: 1px solid #d2d2d2; border-radius: 6px; }
        .metric-value { font-size: 28px; font-weight: 700; display: block; }
        .metric-label { font-size: 11px; color: #6a6e73; }
        .badge { display: inline-block; padding: 2px 8px; border-radius: 10px; font-size: 11px; font-weight: 600; }
        .badge-green { background: #e7f5e1; color: #3e8635; }
        .badge-red { background: #fce7e7; color: #c9190b; }
        .badge-orange { background: #fef3e0; color: #ec7a08; }
        .footer { margin-top: 32px; font-size: 11px; color: #6a6e73; border-top: 1px solid #d2d2d2; padding-top: 8px; }
      </style></head><body>
      <h1>${version} Release Report</h1>
      <p>Generated: ${new Date().toLocaleString()}</p>
      ${reportRef.current.innerHTML}
      <div class="footer">Generated by CNV Console Monitor</div>
      </body></html>
    `);
    printWindow.document.close();
    setTimeout(() => {
      printWindow.print();
    }, 500);
  };

  const slackReport = useMemo(() => {
    const lines: string[] = [];
    lines.push(`:rocket: *${version} Release Status*`);
    if (release.nextRelease) {
      lines.push(
        `> Next: *${release.nextRelease.name}* — ${new Date(release.nextRelease.date).toLocaleDateString()}${release.daysUntilNext !== null ? ` (${release.daysUntilNext}d)` : ''}`,
      );
    }
    lines.push(`*Checklist:* ${closedItems.length}/${totalItems} done (${checklistPct}%)`);
    if (passRate !== null) {
      lines.push(`*Pass Rate:* ${passRate}%`);
    }
    lines.push(
      `*Status:* ${isHealthy ? ':white_check_mark: On Track' : ':warning: Needs Attention'}`,
    );
    if (openItems.length > 0) {
      lines.push(`\n*Open Items (${openItems.length}):*`);
      openItems
        .slice(0, 10)
        .forEach(task =>
          lines.push(
            `• <https://issues.redhat.com/browse/${task.key}|${task.key}> ${task.summary}`,
          ),
        );
      if (openItems.length > 10) {
        lines.push(`_...and ${openItems.length - 10} more_`);
      }
    }
    return lines.join('\n');
  }, [release, version, closedItems, totalItems, checklistPct, passRate, isHealthy, openItems]);

  return (
    <>
      <Button icon={<FileAltIcon />} size="sm" variant="secondary" onClick={() => setIsOpen(true)}>
        Generate Report
      </Button>
      <Modal isOpen={isOpen} variant={ModalVariant.large} onClose={() => setIsOpen(false)}>
        <ModalHeader title={`${version} Release Report`} />
        <ModalBody>
          <Tabs activeKey={activeTab} onSelect={(_e, k) => setActiveTab(k as number)}>
            <Tab eventKey={0} title={<TabTitleText>Visual Report</TabTitleText>}>
              <div className="app-report app-mt-md" ref={reportRef}>
                <Alert
                  isInline
                  className="app-mb-md"
                  title={isHealthy ? 'Release is on track' : 'Release needs attention'}
                  variant={isHealthy ? 'success' : 'warning'}
                />

                <div className="app-report-metrics app-mb-md">
                  <div className="app-report-metric">
                    <span className="app-report-metric-value">{checklistPct}%</span>
                    <span className="app-text-xs app-text-muted">Checklist</span>
                    <Progress
                      className="app-mt-xs"
                      measureLocation={ProgressMeasureLocation.none}
                      size={ProgressSize.sm}
                      value={checklistPct}
                    />
                  </div>
                  <div className="app-report-metric">
                    <span className="app-report-metric-value">
                      {passRate !== null ? `${passRate}%` : '--'}
                    </span>
                    <span className="app-text-xs app-text-muted">Pass Rate</span>
                    {passRate !== null && (
                      <Progress
                        className="app-mt-xs"
                        measureLocation={ProgressMeasureLocation.none}
                        size={ProgressSize.sm}
                        value={passRate}
                      />
                    )}
                  </div>
                  <div className="app-report-metric">
                    <span className="app-report-metric-value">{release.daysUntilNext ?? '--'}</span>
                    <span className="app-text-xs app-text-muted">Days Left</span>
                  </div>
                  <div className="app-report-metric">
                    <span className="app-report-metric-value">{openItems.length}</span>
                    <span className="app-text-xs app-text-muted">Open Items</span>
                  </div>
                </div>

                <DescriptionList isCompact isHorizontal className="app-mb-md">
                  <DescriptionListGroup>
                    <DescriptionListTerm>Version</DescriptionListTerm>
                    <DescriptionListDescription>{version}</DescriptionListDescription>
                  </DescriptionListGroup>
                  <DescriptionListGroup>
                    <DescriptionListTerm>Phase</DescriptionListTerm>
                    <DescriptionListDescription>
                      <Label isCompact>{release.phase}</Label>
                    </DescriptionListDescription>
                  </DescriptionListGroup>
                  {release.nextRelease && (
                    <DescriptionListGroup>
                      <DescriptionListTerm>Next Release</DescriptionListTerm>
                      <DescriptionListDescription>
                        {release.nextRelease.name} —{' '}
                        {new Date(release.nextRelease.date).toLocaleDateString()}
                      </DescriptionListDescription>
                    </DescriptionListGroup>
                  )}
                  <DescriptionListGroup>
                    <DescriptionListTerm>Checklist Progress</DescriptionListTerm>
                    <DescriptionListDescription>
                      {closedItems.length} / {totalItems} completed
                    </DescriptionListDescription>
                  </DescriptionListGroup>
                  {readiness && (
                    <DescriptionListGroup>
                      <DescriptionListTerm>Test Launches</DescriptionListTerm>
                      <DescriptionListDescription>
                        {readiness.totalLaunches} (last 14 days)
                      </DescriptionListDescription>
                    </DescriptionListGroup>
                  )}
                </DescriptionList>

                {openItems.length > 0 && (
                  <>
                    <Divider className="app-mb-md" />
                    <Content className="app-mb-sm" component="h4">
                      Open Items by Priority
                    </Content>
                    {byPriority.map(([priority, items]) => (
                      <div className="app-mb-sm" key={priority}>
                        <Content className="app-mb-xs" component="h5">
                          <Label
                            isCompact
                            color={
                              priority === 'Blocker' || priority === 'Critical'
                                ? 'red'
                                : priority === 'Major'
                                  ? 'orange'
                                  : 'grey'
                            }
                          >
                            {priority}
                          </Label>
                          <span className="app-text-xs app-text-muted app-ml-sm">
                            ({items.length})
                          </span>
                        </Content>
                        {items.map(task => (
                          <div className="app-report-item" key={task.key}>
                            <a
                              className="app-report-key"
                              href={`https://issues.redhat.com/browse/${task.key}`}
                              rel="noreferrer"
                              target="_blank"
                            >
                              {task.key}
                            </a>
                            <span className="app-report-title">{task.summary}</span>
                            <span className="app-text-xs app-text-muted">
                              {task.assignee || 'Unassigned'}
                            </span>
                          </div>
                        ))}
                      </div>
                    ))}

                    <Divider className="app-mb-md app-mt-md" />
                    <Content className="app-mb-sm" component="h4">
                      Workload Distribution
                    </Content>
                    <div className="app-report-workload">
                      {byAssignee.map(([name, count]) => (
                        <Flex
                          alignItems={{ default: 'alignItemsCenter' }}
                          className="app-mb-xs"
                          key={name}
                          spaceItems={{ default: 'spaceItemsSm' }}
                        >
                          <FlexItem style={{ minWidth: 120 }}>
                            <span className="app-text-xs">{name}</span>
                          </FlexItem>
                          <FlexItem flex={{ default: 'flex_1' }}>
                            <Progress
                              measureLocation={ProgressMeasureLocation.none}
                              size={ProgressSize.sm}
                              value={(count / openItems.length) * 100}
                            />
                          </FlexItem>
                          <FlexItem>
                            <span className="app-text-xs app-text-muted">{count}</span>
                          </FlexItem>
                        </Flex>
                      ))}
                    </div>
                  </>
                )}
              </div>
            </Tab>
            <Tab eventKey={1} title={<TabTitleText>Slack Format</TabTitleText>}>
              <ClipboardCopy isBlock className="app-mt-md" variant={ClipboardCopyVariant.expansion}>
                {slackReport}
              </ClipboardCopy>
            </Tab>
          </Tabs>
        </ModalBody>
        <ModalFooter>
          <Button icon={<DownloadIcon />} variant="primary" onClick={handleDownloadPdf}>
            Download PDF
          </Button>
          <Button
            icon={<CopyIcon />}
            variant="secondary"
            onClick={() => navigator.clipboard.writeText(slackReport)}
          >
            Copy Slack
          </Button>
          <Button variant="link" onClick={() => setIsOpen(false)}>
            Close
          </Button>
        </ModalFooter>
      </Modal>
    </>
  );
};
